package com.spring.test.mapper.generator;

import com.spring.test.entry.generator.TxOrder;
import com.spring.test.entry.generator.TxOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TxOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_order
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    int countByExample(TxOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_order
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    int deleteByExample(TxOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_order
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_order
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    int insert(TxOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_order
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    int insertSelective(TxOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_order
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    List<TxOrder> selectByExample(TxOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_order
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    TxOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_order
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") TxOrder record, @Param("example") TxOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_order
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    int updateByExample(@Param("record") TxOrder record, @Param("example") TxOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_order
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    int updateByPrimaryKeySelective(TxOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_order
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    int updateByPrimaryKey(TxOrder record);
}