package com.spring.test.entry.generator;

public class SUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.id
     *
     * @mbggenerated Sat Aug 11 16:13:32 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.name
     *
     * @mbggenerated Sat Aug 11 16:13:32 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.age
     *
     * @mbggenerated Sat Aug 11 16:13:32 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.adress
     *
     * @mbggenerated Sat Aug 11 16:13:32 CST 2018
     */
    private String adress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.id
     *
     * @return the value of s_user.id
     *
     * @mbggenerated Sat Aug 11 16:13:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.id
     *
     * @param id the value for s_user.id
     *
     * @mbggenerated Sat Aug 11 16:13:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.name
     *
     * @return the value of s_user.name
     *
     * @mbggenerated Sat Aug 11 16:13:32 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.name
     *
     * @param name the value for s_user.name
     *
     * @mbggenerated Sat Aug 11 16:13:32 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.age
     *
     * @return the value of s_user.age
     *
     * @mbggenerated Sat Aug 11 16:13:32 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.age
     *
     * @param age the value for s_user.age
     *
     * @mbggenerated Sat Aug 11 16:13:32 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.adress
     *
     * @return the value of s_user.adress
     *
     * @mbggenerated Sat Aug 11 16:13:32 CST 2018
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.adress
     *
     * @param adress the value for s_user.adress
     *
     * @mbggenerated Sat Aug 11 16:13:32 CST 2018
     */
    public void setAdress(String adress) {
        this.adress = adress;
    }
}