package com.spring.test.entry.generator;

public class TxOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_order.id
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_order.name
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_order.money
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_order.id
     *
     * @return the value of tx_order.id
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_order.id
     *
     * @param id the value for tx_order.id
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_order.name
     *
     * @return the value of tx_order.name
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_order.name
     *
     * @param name the value for tx_order.name
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_order.money
     *
     * @return the value of tx_order.money
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_order.money
     *
     * @param money the value for tx_order.money
     *
     * @mbggenerated Mon Oct 22 17:22:01 CST 2018
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}